from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum, str
from typing import Optional, List


from enum import Enum

class Governorates(str, Enum):
    CAIRO = 'Cairo'
    GIZA = 'Giza'
    ALEXANDRIA = 'Alexandria'
    DAKAHLIA = 'Dakahlia'
    RED_SEA = 'Red Sea'
    BEHEIRA = 'Beheira'
    FAYOUM = 'Fayoum'
    GHARBIYA = 'Gharbiya'
    ISMAILIA = 'Ismailia'
    MENOFIA = 'Menofia'
    MINYA = 'Minya'
    QALIUBIYA = 'Qaliubiya'
    NEW_VALLEY = 'New Valley'
    SUEZ = 'Suez'
    ASWAN = 'Aswan'
    ASSIUT = 'Assiut'
    BENI_SUEF = 'Beni Suef'
    PORT_SAID = 'Port Said'
    DAMIETTA = 'Damietta'
    SHARKIA = 'Sharkia'
    SOUTH_SINAI = 'South Sinai'
    NORTH_SINAI = 'North Sinai'
    KAFR_EL_SHEIKH = 'Kafr el-Sheikh'
    MATROUH = 'Matrouh'
    LUXOR = 'Luxor'
    QENA = 'Qena'
    SOHAG = 'Sohag'


class AlexandriaCities(str, Enum):
    AGAMI = 'Agami'
    MIAMI = 'Miami'
    MONTAZAH = 'Montazah'
    MANDARA = 'Mandara'
    ASAFRA = 'Asafra'
    MAAMOURA = 'Maamoura'
    ABU_QIR = 'Abu Qir'
    
    RAML_STATION = 'Raml Station'
    MANSHIYYA = 'Manshiyya'
    ATTARIN = 'Attarin'
    GOMROK = 'Gomrok'
    LABBAN = 'Labban'
    KARMOUS = 'Karmous'
    
    SIDI_BESHR = 'Sidi Beshr'
    SIDI_GABER = 'Sidi Gaber'
    SPORTING = 'Sporting'
    STANLEY = 'Stanley'
    RUSHDY = 'Roushdy'
    KAFR_ABDO = 'Kafr Abdo'
    CLEOPATRA = 'Cleopatra'
    SABA_PASHA = 'Saba Pasha'
    VICTORIA = 'Victoria'
    ZEZENIA = 'Zezenia'
    BOLKLY = 'Bolkly'
    SAN_STEFANO = 'San Stefano'
    
    DEKHEILA = 'Dekheila'
    EL_MAX = 'El Max'
    WARDIAN = 'Wardian'
    MINA_EL_BASAL = 'Mina El Basal'
    
    SHATBY = 'Shatby'
    AZARITA = 'Azarita'
    IBRAHIMIYYA = 'Al Ibrahimiyyah'
    HADRAH = 'Al Hadrah'
    SMOHA = 'Smoha'
    SEYOUF = 'Seyouf'
    FLEMING = 'Fleming'
    CAMP_CAESAR = 'Camp Caesar'
    MOHARAM_BEK = 'Moharam Bik'
    
    AMREYA = 'Amreya'
    BORG_EL_ARAB = 'Borg al-Arab'
    KING_MARIOUT = 'King Mariout'
    
    BACCHUS = 'Bacchus'
    LAURENT = 'Laurent'
    SCHUTZ = 'Schutz'
    GIANACLIS = 'Gianaclis'
    SALEHIA = 'Salehia'
    GLIM = 'Glim'
    OTHER = 'Others'


class aswanCities(str, Enum):
   ASWAN_CITY = 'Aswan City'
   KOM_OMBO = 'Kom Ombo'
   EDFU = 'Edfu'
   ABOU_AL_REISH = 'Abou al-Reish' 
   SEBAEIAH = 'Sebaeiah'
   ABOU_SIMBEL = 'Abou Simbel'
   BASILIAH = 'Basiliah'
   DARAW = 'Daraw'
   KALABSHA = 'Kalabsha' 
   NASR_AL_NOBA = 'Nasr al-Noba'
   RDESIAH = 'Rdesiah'
   SAHARA = 'Sahara'
   OTHER = 'Others'


class asyutCities(str, Enum):
   ASYUT_CITY = 'Asyut City'
   DAIRUT = 'Dairut'
   MANFALUT = 'Manfalut'
   FATEH = 'Fateh'
   SEDFA = 'Sedfa'
   ABNUB = 'Abnub'
   ABU_TEEG = 'Abu Teeg'
   BADARI = 'Badari'
   GHANAYEM = 'Ghanayem'
   NEW_ASSIUT = 'New Assiut'
   NEW_TIBA = 'New Tiba'
   QUSIYA = 'Qusiya'
   SAHEL_SELIM = 'Sahel Selim'
   OTHER = 'Others'


class beheiraCities(str, Enum):
    ABOU_HOMS = 'Abou Homs'
    ABUU_AL_MATAMER = 'Abuu al-Matamer'
    AL_NUBARIYAH = 'Al Nubariyah'
    DAMANHOUR = 'Damanhour'
    DELENGAT = 'Delengat'
    EDKO = 'Edko'
    ETAY_AL_BARUD = 'Etay al-Barud'
    HOSH_ESSA = 'Hosh Essa'
    KAFR_AL_DAWWAR = 'Kafr al-Dawwar'
    KOM_HAMADAH = 'Kom Hamadah'
    MAHMOUDIYAH = 'Mahmoudiyah'
    MARKAZ_BADR = 'Markaz Badr'
    NUBARIYAH = 'Nubariyah'
    RAHMANIYA = 'Rahmaniya'
    RASHID = 'Rashid'
    SHUBRAKHIT = 'Shubrakhit'
    WADI_AL_NATRUN = 'Wadi al-Natrun'
    OTHER = 'Others'



class beniSuefCities(str, Enum):
    BENI_SUEF_CITY = 'Beni Suef City'
    NEW_BENI_SUEF = 'New Beni Suef'
    BEBA = 'Beba'
    EHNASIA = 'Ehnasia'
    AL_FESHN = 'Al Feshn'
    AL_WASTY = 'Al Wasty'
    NASSER = 'Nasser'
    SAMASTA = 'Samasta'
    OTHER = 'Others'


class cairoCities(str, Enum):
    NASR_CITY = 'Nasr City'
    NEW_CAIRO = 'New Cairo'
    MAADI = 'Maadi'
    HELIOPOLIS = 'Heliopolis'
    AIN_SHAMS = 'Ain Shams'
    OTHERS = 'Others'
    MAY_15_CITY = '15 May City'
    ABASIYA = 'Abasiya'
    AL_AMIRIYYAH = 'Al Amiriyyah'
    AL_MANIAL = 'Al Manial'
    ALMAZAH = 'Almazah'
    ATABA = 'Ataba'
    BAB_AL_SHEREIA = 'Bab al-Shereia'
    BADR_CITY = 'Badr City'
    BASATEEN = 'Basateen'
    BOULAQ_ABO_EL_ELA = 'Boulaq Abo El Ela'
    DAR_AL_SALAAM = 'Dar al-Salaam'
    DARB_AL_AHMAR = 'Darb al-Ahmar'
    DARRASA = 'Darrasa'
    DOWNTOWN_CAIRO = 'Downtown Cairo'
    EL_FOSTAT = 'El Fostat'
    EZBET_EL_NAKHL = 'Ezbet El Nakhl'
    GAMALEYA = 'Gamaleya'
    GARDEN_CITY = 'Garden City'
    GESR_AL_SUEZ = 'Gesr Al Suez'
    HADAYEK_HELWAN = 'Hadayek Helwan'
    HADAYEK_AL_KOBBA = 'Hadayek al-Kobba'
    HADAYEQ_EL_ZEITOUN = 'Hadayeq El Zeitoun'
    HELMEYA_AL_GADEDA = 'Helmeya al-Gadeda'
    HELMEYAT_EL_ZAYTOUN = 'Helmeyat El Zaytoun'
    HELWAN = 'Helwan'
    KATAMEYA = 'Katameya'
    LOC_3 = 'Loc 3'
    MASARA = "Ma'sara"
    MADINATY = 'Madinaty'
    MARG = 'Marg'
    MASR_AL_KADEEMA = 'Masr al-Kadema'
    MATAREYA = 'Matareya'
    MOKATTAM = 'Mokattam'
    MOSKI = 'Moski'
    MOSTAKBAL_CITY = 'Mostakbal City'
    NEW_CAPITAL_CITY = 'New Capital City'
    NEW_HELIOPOLIS = 'New Heliopolis'
    NEW_NOZHA = 'New Nozha'
    OBOUR_CITY = 'Obour City'
    QASR_AL_NIL = 'Qasr al-Nil'
    RAMSES = 'Ramses + Ramses Extension'
    ROD_AL_FARAG = 'Rod al-Farag'
    SALAM_CITY = 'Salam City'
    SAYEDA_ZEINAB = 'Sayeda Zeinab'
    SHARABEYA = 'Sharabeya'
    SHERATON = 'Sheraton'
    SHOROUK_CITY = 'Shorouk City'
    SHUBRA = 'Shubra'
    TEBEEN = 'Tebeen'
    TURA = 'Tura'
    WAILI = 'Waili'
    ZAHRAA_AL_MAADI = 'Zahraa Al Maadi'
    ZAMALEK = 'Zamalek'
    ZAWYA_AL_HAMRA = 'Zawya al-Hamra'



class damiettaCities(str, Enum):
    DAMIETTA_CITY = 'Damietta City'
    NEW_DAMIETTA = 'New Damietta'
    RAS_AL_BAR = 'Ras al-Bar'
    KAFR_SAAD = 'Kafr Saad'
    FARESKOUR = 'Fareskour'
    EZBET_AL_BURJ = 'Ezbet al-Burj'
    KAFR_AL_BATEEKH = 'Kafr al-Bateekh'
    MARKAZ_EL_RODAH = 'Markaz El Rodah'
    MIT_ABUGHALB = 'Mit Abughalb'
    SARO = 'Saro'
    ZARQA = 'Zarqa'
    OTHER = 'Others'

class dakahliaCities(str, Enum):

    MANSURA = 'Mansura'
    MIT_GHAMR = 'Mit Ghamr'
    AGA = 'Aga'
    TALKHA = 'Talkha'
    SINBILLAWAIN = 'Sinbillawain'
    OTHERS = 'Others'
    AKHTAB = 'Akhtab'
    BANI_UBAYD = 'Bani Ubayd'
    BELQAS = 'Belqas'
    DIKIRNIS = 'Dikirnis'
    EL_KORDY = 'El Kordy'
    GAMASA = 'Gamasa'
    MANZALA = 'Manzala'
    MARKAZ_EL_GAMALEYA = 'Markaz El Gamaleya'
    MARKAZ_EL_MATAREYA = 'Markaz El Matareya'
    MINAT_AL_NASR = 'Minat al-Nasr'
    MIT_SLSEEL = 'Mit Slseel'
    NABARUH = 'Nabaruh'
    NEW_MANSOURA = 'New Mansoura'
    SHIRBIN = 'Shirbin'
    TAMA_AL_AMDEED = 'Tama al-Amdeed'



class FayoumCities(str, Enum):
    FAYOUM_CITY = 'Fayoum City'
    IBSHWAY = 'Ibshway'
    ATSSA = 'Atssa'
    TAMIYA = 'Tamiya'
    SINNURAS = 'Sinnuras'
    OTHERS = 'Others'
    NEW_FAYOUM = 'New Fayoum'
    YUSUF_AL_SADIQ = 'Yusuf al-Sadiq'


class GharbiaCities(str, Enum):
    TANTA = 'Tanta'
    MAHALLA_AL_KOBRA = 'Mahalla al-Kobra'
    ZEFTA = 'Zefta'
    KAFR_AL_ZAYAT = 'Kafr al-Zayat'
    SANTA = 'Santa'
    OTHERS = 'Others'
    BASYOUN = 'Basyoun'
    QUTOUR = 'Qutour'
    SAMANOUD = 'Samanoud'



class GizaCities(str, Enum):
    SIXTH_OF_OCTOBER = '6th of October'
    HARAM = 'Haram'
    FAISAL = 'Faisal'
    SHEIKH_ZAYED = 'Sheikh Zayed'
    IMBABA = 'Imbaba'
    OTHERS = 'Others'
    ABU_RAWASH = 'Abu Rawash'
    AGOUZA = 'Agouza'
    ARD_EL_LEWA = 'Ard El Lewa'
    BADRASHEEN = 'Badrasheen'
    BARAGIL = 'Baragil'
    BASHTIL = 'Bashtil'
    BOULAQ_DAKROUR = 'Boulaq Dakrour'
    DAHAB_ISLAND = 'Dahab Island'
    DAHSHUR = 'Dahshur'
    DOKKI = 'Dokki'
    EL_AYYAT = 'El Ayyat'
    GIZA_DISTRICT = 'Giza District'
    HADAYEK_OCTOBER = 'Hadayek October'
    HADAYEK_AL_AHRAM = 'Hadayek al-Ahram'
    HAWAMDEYA = 'Hawamdeya'
    KERDASA = 'Kerdasa'
    KIT_KAT = 'Kit Kat'
    MANIAL_SHIHA = 'Manial Shiha'
    MANSURIYYA = 'Mansuriyya'
    MARKAZ_AL_GIZA = 'Markaz al-Giza'
    MARYOTAYA = 'Maryotaya'
    MOHANDESSIN = 'Mohandessin'
    MONEEB = 'Moneeb'
    NAHIA = 'Nahia'
    OSEEM = 'Oseem'
    SAF = 'Saf'
    SAFT_EL_LABAN = 'Saft El Laban'
    TERSA = 'Tersa'
    WARRAQ = 'Warraq'


class IsmailiaCities(str, Enum):
    ISMAILIA_CITY = 'Ismailia City'
    FAYED = 'Fayed'
    KANTARA_WEST = 'Kantara West'
    ABU_SWEAR = 'Abu Swear'
    QASSASEEN = 'Qassaseen'
    OTHERS = 'Others'
    KANTARA_EAST = 'Kantara East'
    TAL_AL_KEBEER = 'Tal al-Kebeer'


class KafrAlSheikhCities(str, Enum):
    KAFR_AL_SHEIKH_CITY = 'Kafr al-Sheikh City'
    DESOUK = 'Desouk'
    SIDI_SALEM = 'Sidi Salem'
    BALTIM = 'Baltim'
    QALEEN = 'Qaleen'
    OTHERS = 'Others'
    BELLA = 'Bella'
    BROLOS = 'Brolos'
    FOUH = 'Fouh'
    HAMOUL = 'Hamoul'
    MOTOBAS = 'Motobas'
    RIYADH = 'Riyadh'

class LuxorCities(str, Enum):
    LUXOR_CITY = 'Luxor City'
    ISNA = 'Isna'
    ARMANT = 'Armant'
    TOD = 'Tod'
    OTHERS = 'Others'
    BAYADEYA = 'Bayadeya'
    QURNA = 'Qurna'
    ZINNIA = 'Zinnia'

class MatrouhCities(str, Enum):
    MARSA_MATROUH = 'Marsa Matrouh'
    NORTH_COAST = 'North Coast'
    ALAMEIN = 'Alamein'
    DABAA = 'Dabaa'
    SIWA = 'Siwa'
    OTHERS = 'Others'
    BARANY = 'Barany'
    HAMMAM = 'Hammam'
    NAGELA = 'Nagela'
    SALLOUM = 'Salloum'


class MinyaCities(str, Enum):
    MINYA_CITY = 'Minya City'
    NEW_MINYA = 'New Minya'
    MALAWI = 'Malawi'
    SAMALUT = 'Samalut'
    ABU_QURQAS = 'Abu Qurqas'
    OTHERS = 'Others'
    ADWA = 'Adwa'
    BENI_MAZAR = 'Beni Mazar'
    DEIR_MAWAS = 'Deir Mawas'
    MAGHAGHA = 'Maghagha'
    MATAY = 'Matay'


class MonufiaCities(str, Enum):
    SHEBIN_AL_KOUM = 'Shebin al-Koum'
    SADAT = 'Sadat'
    QUESNA = 'Quesna'
    MENOUF = 'Menouf'
    ASHMON = 'Ashmon'
    OTHERS = 'Others'
    BAGOUR = 'Bagour'
    BERKET_AL_SABAA = 'Berket al-Sabaa'
    SERS_AL_LYAN = 'Sers al-Lyan'
    SHOHADAA = 'Shohadaa'
    TALA = 'Tala'


class NewValleyCities(str, Enum):
    KHARGA = 'Kharga'
    OTHERS = 'Others'
    BALAT = 'Balat'
    DAKHLA = 'Dakhla'
    FARAFRA = 'Farafra'
    MUT = 'Mut'
    PARIS = 'Paris'



class PortSaidDistricts(str, Enum):
    SHARQ_DISTRICT = 'Sharq District'
    PORT_FOUAD = 'Port Fouad'
    ZOHOUR_DISTRICT = 'Zohour District'
    DAWAHY_DISTRICT = 'Dawahy District'
    MANAKH_DISTRICT = 'Manakh District'
    OTHERS = 'Others'
    ARAB_DISTRICT = 'Arab District'
    GANOUB_DISTRICT = 'Ganoub District'


class QalyubiaCities(str, Enum):
    SHUBRA_AL_KHAIMAH = 'Shubra al-Khaimah'
    BANHA = 'Banha'
    KHOSOUS = 'Khosous'
    KHANKA = 'Khanka'
    BAHTIM = 'Bahtim'
    OTHERS = 'Others'
    KAFR_SHUKR = 'Kafr Shukr'
    MUSTURAD = 'Musturad'
    QAHA = 'Qaha'
    QALYUB = 'Qalyub'
    QANATER_AL_KHAIRIA = 'Qanater al-Khairia'
    SHEBIN_AL_QANATER = 'Shebin al-Qanater'
    TOOKH = 'Tookh'


class QenaCities(str, Enum):
    QENA_CITY = 'Qena City'
    NAG_HAMMADI = 'Nag Hammadi'
    QUOS = 'Quos'
    KEFT = 'Keft'
    DISHNA = 'Dishna'
    OTHERS = 'Others'
    ABU_TISHT = 'Abu Tisht'
    FARSHOUT = 'Farshout'
    NAKADA = 'Nakada'
    WAKF = 'Wakf'


class RedSeaCities(str, Enum):
    HURGHADA = 'Hurghada'
    GOUNA = 'Gouna'
    SAFAGA = 'Safaga'
    MARSA_ALAM = 'Marsa Alam'
    OTHERS = 'Others'
    HALAYEB_AND_SHALATEEN = 'Halayeb & Shalateen'
    MAKADI_BAY = 'Makadi Bay'
    QUSAIR = 'Qusair'
    RAS_GHARIB = 'Ras Gharib'
    RAS_SOMA = 'Ras Soma'
    SAHL_HASHEESH = 'Sahl Hasheesh'
    SOMA_BAY = 'Soma Bay'



class SharqiaCities(str, Enum):
    ZAGAZIG = 'Zagazig'
    TENTH_OF_RAMADAN = '10th of Ramadan'
    BILBEIS = 'Bilbeis'
    FAQOUS = 'Faqous'
    MINYA_AL_QAMH = 'Minya al-Qamh'
    OTHERS = 'Others'
    ABU_HAMMAD = 'Abu Hammad'
    ABU_KABIR = 'Abu Kabir'
    ALQNAYAT = 'Alqnayat'
    AWLAD_SAQR = 'Awlad Saqr'
    DEYERB_NEGM = 'Deyerb Negm'
    HIHYA = 'Hihya'
    HUSSEINIYA = 'Husseiniya'
    IBRAHEMYAH = 'Ibrahemyah'
    KAFR_SAQR = 'Kafr Saqr'
    MASHTOOL_AL_SOUK = 'Mashtool al-Souk'
    NEW_SALHIA = 'New Salhia'
    QAREEN = 'Qareen'



class SohagCities(str, Enum):
    MARKAZ_SOHAG = 'Markaz Sohag'
    AKHMIM = 'Akhmim'
    GIRGA = 'Girga'
    TAHTA = 'Tahta'
    TAMA = 'Tama'
    OTHERS = 'Others'
    ALASIRAT = 'Alasirat'
    BALIANA = 'Baliana'
    MARAGHA = 'Maragha'
    MARKAZ_DAR_EL_SALAM = 'Markaz Dar El Salam'
    MARKAZ_JUHAYNAH = 'Markaz Juhaynah'
    MONSHA_A = 'Monsha\'a'
    NEW_SOHAG = 'New Sohag'
    SAKALTAH = 'Sakaltah'



class SouthSinaiCities(str, Enum):
    SHARM_AL_SHEIKH = 'Sharm al-Sheikh'
    TOR_SINAI = 'Tor Sinai'
    DAHAB = 'Dahab'
    RAS_SEDR = 'Ras Sedr'
    OTHERS = 'Others'
    ABU_RUDEIS = 'Abu Rudeis'
    ABU_ZENIMAH = 'Abu Zenimah'
    NUWEIBA = 'Nuweiba'
    ST_CATHERINE = 'St. Catherine'
    TABA = 'Taba'



class SuezDistricts(str, Enum):
    SUEZ_DISTRICT = 'Suez District'
    ARBAEEN = 'Arbaeen'
    ATTAKA = 'Attaka'
    FAISAL_DISTRICT = 'Faisal District'
    GANAYEN = 'Ganayen'
    OTHERS = 'Others'
    AIN_SUKHNA = 'Ain Sukhna'




